# pre-release or release builds from tag
- job:
    name: 'Release-Build'
    node: 'master'
    project-type: multijob

    wrappers:
      - timestamps
      - build-user-vars

    parameters:
      - string:
          name: EMAIL
          default: $BUILD_USER_EMAIL
          description: "Comma separated destination for results (default: https://jenkins.esgyn.com/me/configure)"
      - string:
          name: TAG
          description: "Git tag to build against"
      - choice:
          name: BRANCH
          choices:
            - master
            - release1.3
            - release2.0
          default: master
          description: "Release Branch"
      - choice:
          name: TAGTYPE
          choices:
            - pre-release
            - release
          default: pre-release
          description: "Type of Tag / Build"


    scm:
      - git:
          url: https://github.com/apache/incubator-trafodion
          wipe-workspace: false
          skip-tag: true
          branches:
            - refs/tags/$TAG


    builders:
      - inject:
          properties-content: |
            LOG_PATH=Release/$TAG/$BUILD_NUMBER
      - link-logs
      - multijob:
          name: build
          projects:
            - name: "build-label"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/build-label
                 BUILD_TYPE=$TAGTYPE
                 TAG=$TAG

    publishers:
      - console-log
      - postbuildscript:
          script-only-if-succeeded: false
          script-only-if-failed: false
          builders:
            - shell: "/usr/local/bin/job-summary.sh"
      - email-ext:
          recipients: $EMAIL
          reply-to: no-reply@trafodion.org
          content-type: "text"
          subject: Trafodion Release Build $TAGTYPE $TAG
          save-output: true
          always: true
          failure: false
          body: |
            Release Automated Testing $TAGTYPE $TAG

            Jenkins Job:   $BUILD_URL
            Archived Logs: http://traf-testlogs.esgyn.com/$LOG_PATH
            Bld Downloads: http://traf-builds.esgyn.com/
            
            Test Job Results:
            
            ${FILE,path="build_result.txt"}

# Mechanism for developers to choose tests

- job:
    name: 'Requested-Test'
    node: 'master'
    project-type: multijob

    wrappers:
      - timestamps
      - build-user-vars

    parameters:
      - string:
          name: EMAIL
          default: $BUILD_USER_EMAIL
          description: "Comma separated destination for results (default: https://jenkins.esgyn.com/me/configure)"
      - string:
          name: PULL_NUM
          description: "Pull Request Number"
      - string:
          name: BRANCH
          default: master
          description: "Target Branch of the Pull Request"
      - choice:
          name: DISTRO
          choices:
            - cm5.4
            - ahw2.3
            - va1.0
          description: "Distro: AmbariHortonWorks or ClouderaManager"
      - bool:
          name: sql
          default: false
          description: Run SQL regression?
      - string:
          name: sql_tests
          default:  "privs1 privs2 charsets executor fullstack2 qat hive compGeneral udr"
          description: "Space separated list of suites. Non-default: core seabase"
      - bool:
          name: pyodbc
          default: false
          description: Run Python ODBC tests?
      - bool:
          name: jdbc
          default: false
          description: Run JDBC tests?
      - bool:
          name: phoenix
          default: false
          description: Run Phx tests?
      - choice:
          name: Phx_Driver
          choices:
            - T4
            - T2
          description: "Driver type to use for Phoenix"

    properties:
      - github:
          url: https://github.com/apache/incubator-trafodion


    builders:
      - inject:
          properties-content: |
            LOG_PATH=Requested/$BUILD_NUMBER
      - link-logs
      - multijob:
          name: tests
          projects:
            - name: "core-regress-hdp"
              enable-condition: "'${sql}' == 'true' && '${DISTRO}' == 'ahw2.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/regress-${DISTRO}
                SUITES=${sql_tests}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "core-regress-cdh"
              enable-condition: "'${sql}' == 'true' && '${DISTRO}' == 'cm5.4'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/regress-${DISTRO}
                SUITES=${sql_tests}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "core-regress-apc"
              enable-condition: "'${sql}' == 'true' && '${DISTRO}' == 'va1.0'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/regress-${DISTRO}
                SUITES=${sql_tests}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "pyodbc_test-hdp"
              enable-condition: "'${pyodbc}' == 'true' && '${DISTRO}' == 'ahw2.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/pyodbc_test-${DISTRO}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "pyodbc_test-cdh"
              enable-condition: "'${pyodbc}' == 'true' && '${DISTRO}' == 'cm5.4'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/pyodbc_test-${DISTRO}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "jdbc_test-hdp"
              enable-condition: "'${jdbc}' == 'true' && '${DISTRO}' == 'ahw2.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/jdbc_test-${DISTRO}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "jdbc_test-cdh"
              enable-condition: "'${jdbc}' == 'true' && '${DISTRO}' == 'cm5.4'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/jdbc_test-${DISTRO}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "jdbc_test-apc"
              enable-condition: "'${jdbc}' == 'true' && '${DISTRO}' == 'va1.0'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/jdbc_test-${DISTRO}
                BRANCH=$BRANCH
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "phoenix_test_T4-hdp"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T4' && '${DISTRO}' == 'ahw2.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
                BRANCH=$BRANCH
                HDIST=$DISTRO
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "phoenix_test_T2-hdp"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T2' && '${DISTRO}' == 'ahw2.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
                BRANCH=$BRANCH
                HDIST=$DISTRO
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "phoenix_test_T4-cdh"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T4' && '${DISTRO}' == 'cm5.4'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
                BRANCH=$BRANCH
                HDIST=$DISTRO
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"
            - name: "phoenix_test_T2-cdh"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T2' && '${DISTRO}' == 'cm5.4'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
                BRANCH=$BRANCH
                HDIST=$DISTRO
              node-label-name: "NODE_TYPE"
              node-label: "redhat_$DISTRO"

    publishers:
      - console-log
      - postbuildscript:
          script-only-if-succeeded: false
          script-only-if-failed: false
          builders:
            - shell: "/usr/local/bin/job-summary.sh"
      - email-ext:
          recipients: $EMAIL
          reply-to: no-reply@trafodion.org
          content-type: "text"
          subject: Trafodion Test Result - PR$PULL_NUM - $BUILD_ID
          save-output: true
          always: true
          body: |
            Requested Automated Testing

            Jenkins Job:   $BUILD_URL
            Archived Logs: http://traf-testlogs.esgyn.com/$LOG_PATH
            
            Test Job Results:
            
            ${FILE,path="build_result.txt"}

# run multiple suites on single slave
# this reduces overhead of installing, etc
# and also reduces machines consumed by manual test requests
- job-group:
    name: 'core-regress-req'

    dist:
      - cdh
      - hdp
      - apc
    jobs:
      - core-regress-{dist}

- job-template:
    name: 'core-regress-{dist}'

    wrappers:
      - timeout:
          timeout: 600
          fail: true
      - timestamps

    parameters:
      - string:
          name: LOG_PATH
      - string:
          name: SUITES
          description: "Space separated list of test suites"
      - string:
          name: BRANCH
          description: "Branch built against"
      - label:
          name: NODE_TYPE

    builders:
      - link-logs
      - check-node
      - kill-traf
      - clean-testspace
      - get-build:
           flavor: "release"
           branch: "$BRANCH"
      - sql-regress:
           dir: "./trafodion/core"
           suites: "$SUITES"

    publishers:
      - post-check-node
      - console-log
      - traf-regress-log
      - copy-system-logs
      - traf-runtime-log

