includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: IndependentPipelineManager
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
          require-approval:
            - verified: [-1, 0]
              username: jenkins
        # From openstack-infra/config SHA-1: 06aada389aa1ceba23bb04b2020689b0d9f06c44
        # Rerun check on change if the results are > 3 days. This is triggered by any activity on the change
        # (in the form of anyone or any bot leaving comments).This should help detect merge conflicts earlier and also let
        # the author know when the patch has zero chances of merging see
        # http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background
        - event: comment-added
          require-approval:
            - username: jenkins
              older-than: 72h
        # From openstack-infra/config SHA-1 :  20f5d2d0034641bc96e822c6846d3b5886dbe119
        # To support the removing of non-integrated jobs (not integrated in 3 days) from gate where their failure is much more expensive.
        # To prevent patches that have been approved with very old checks (older than 3 days) from going to gate where their failure is
        # much more expensive (see http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background)
        - event: comment-added
          require-approval:
            - workflow: 1
            - username: jenkins
              older-than: 72h
        # If check failed, but we get approval, run check again. If it passes, gate will trigger.
        - event: comment-added
          require-approval:
            - verified: -1
          approval:
            - workflow: 1
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: DependentPipelineManager
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        # must have passed check, but might have failed gate
        - verified: [-2, 1, 2]
          newer-than: 72h
        - workflow: 1
    trigger:
      gerrit:
        # event is approval
        - event: comment-added
          approval:
            - workflow: 1
        # event is code-review, already approved
        - event: comment-added
          approval:
            - code-review: 2
        # event is check test pass, already approved
        - event: comment-added
          approval:
            - verified: 1
        # event is reverify comment, already approved
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags 1.1+
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/1.([1-9]+\.)+[0-9]*(_v[0-9]+)?(alpha|beta|candidate|rc|a|b|c|r|g)[0-9]*$
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Test Failures'

  - name: release
    description: When a commit is tagged as a release 1.1+
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/1.([1-9]+\.)+[0-9]+(_v[0-9]+)?$

  - name: pre-release-stable
    description: This pipeline runs jobs on projects in response to pre-release tags 1.0.*
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/1.0.([0-9]+\.)+(_v[0-9]+)?(alpha|beta|candidate|rc|a|b|c|r|g)[0-9]*$
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Test Failures'

  - name: release-stable
    description: When a commit is tagged as a release 1.0.*
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/1.0.([0-9]+\.)+(_v[0-9]+)?$

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$

  - name: check-full
    description: On-demand extensive check testing. Leave review comment "run check-full".
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*run check-full\s*
    success:
      gerrit: {}
    failure:
      gerrit: {}

  - name: daily
    description: Jobs in this queue are triggered daily.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '30 8 * * *'
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build {change.start_datetime} of {change.project} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build {change.start_datetime} of {change.project} -- Test Failures'

jobs:
  - name: ^.*$
    parameter-function: set_log_url
  - name: ^.*-experimental.*$
    voting: false
  - name: ^.*_T2-.*$
    voting: false
  - name: ^.*-jjb-lint
    voting: false
  # daily build will have no branch, so will not skip any configs
  # daily also defaults to master, so make sure jobs are compatible
  - name: ^.*-ahw2.2$
    skip-if:
      - branch: ^stable/1.0$
  - name: ^.*-cm5.3$
    skip-if:
      - branch: ^stable/1.0$
  - name: ^.*-ahw2.1$
    skip-if:
      - branch: ^master$
  - name: ^.*-cm5.1$
    skip-if:
      - branch: ^master$

project-templates:
  - name: core-distro
    check:
      - core-regress-core-{HW}
      - core-regress-seabase-{HW}
      - phoenix_quick_T4-{HW}
      - core-build-check-{HW}
      - jdbc_test-{Cld}
      - pyodbc_test-{Cld}
      - gate-core-check-for-binary
    gate:
      - core-regress-core-{HW}
      - core-regress-seabase-{HW}
      - phoenix_quick_T4-{HW}
      - core-build-check-{HW}
      - jdbc_test-{Cld}
      - pyodbc_test-{Cld}
      - gate-core-check-for-binary
    check-full:
      - phoenix_test_T4-{Cld}
      - phoenix_test_T2-{HW}
      - core-regress-charsets-{Cld}
      - core-regress-qat-{Cld}
      - core-regress-udr-{Cld}
      - core-regress-catman1-{HW}
      - core-regress-compGeneral-{HW}
      - core-regress-executor-{HW}
      - core-regress-fullstack2-{Cld}
      - core-regress-hive-{HW}

  - name: dcs-distro
    check:
      - gate-dcs-check-for-binary
      - dcs-build-{Cld}
      - phoenix_quick_T4-{HW}
      - pyodbc_test-{HW}
      - pyodbc_test-{Cld}
      - jdbc_test-{HW}
      - jdbc_test-{Cld}
    gate:
      - gate-dcs-check-for-binary
      - dcs-build-{Cld}
      - phoenix_quick_T4-{HW}
      - pyodbc_test-{HW}
      - pyodbc_test-{Cld}
      - jdbc_test-{HW}
      - jdbc_test-{Cld}
    check-full:
      - phoenix_test_T4-{Cld}
      - phoenix_test_T2-{Cld}
      - phoenix_test_T4-{HW}
      - phoenix_test_T2-{HW}

  - name: phxtest-distro
    check:
      - gate-phoenix_test-check-for-binary
      - phoenix_part1_T4-{HW}
      - phoenix_part2_T4-{Cld}
      - phoenix_part1_T2-{Cld}
      - phoenix_part2_T2-{HW}

    gate:
      - gate-phoenix_test-check-for-binary
      - phoenix_part1_T4-{HW}
      - phoenix_part2_T4-{Cld}
      - phoenix_part1_T2-{Cld}
      - phoenix_part2_T2-{HW}


projects:
  - name: trafodion/sandbox
    check:
      - gate-sandbox-check-for-binary
    gate:
      - gate-sandbox-check-for-binary
    silent:
      - gate-sandbox-puppet-lint
      - gate-sandbox-puppet-syntax
      - gate-sandbox-jjb-lint

  - name: trafodion/core
    template:
     - name: core-distro
       HW: ahw2.1
       Cld: cm5.1
     - name: core-distro
       HW: ahw2.2
       Cld: cm5.3
    daily:
      - traf-pub-release-ahw2.2
      - traf-pub-debug-ahw2.2
      - core-regress-core-cm5.3
      - core-regress-core-ahw2.2
      - core-regress-charsets-cm5.3
      - core-regress-charsets-ahw2.2
      - core-regress-qat-cm5.3
      - core-regress-qat-ahw2.2
      - core-regress-udr-cm5.3
      - core-regress-udr-ahw2.2
      - core-regress-catman1-cm5.3
      - core-regress-catman1-ahw2.2
      - core-regress-compGeneral-cm5.3
      - core-regress-compGeneral-ahw2.2
      - core-regress-executor-cm5.3
      - core-regress-executor-ahw2.2
      - core-regress-fullstack2-cm5.3
      - core-regress-fullstack2-ahw2.2
      - core-regress-hive-cm5.3
      - core-regress-hive-ahw2.2
      - core-regress-seabase-cm5.3
      - core-regress-seabase-ahw2.2
      - phoenix_part1_T4-cm5.3
      - phoenix_part2_T4-cm5.3
      - phoenix_part1_T4-ahw2.2
      - phoenix_part2_T4-ahw2.2
      - phoenix_part1_T2-cm5.3
      - phoenix_part2_T2-cm5.3
      - phoenix_part1_T2-ahw2.2
      - phoenix_part2_T2-ahw2.2
      - pyodbc_test-cm5.3
      - pyodbc_test-ahw2.2
      - jdbc_test-cm5.3
      - jdbc_test-ahw2.2
    release:
      - traf-pub-release-ahw2.2
    release-stable:
      - traf-pub-release-ahw2.1
    pre-release:
      - traf-pub-release-ahw2.2
      - traf-pub-debug-ahw2.2
      - phoenix_test_T4-cm5.3
      - phoenix_test_T2-ahw2.2
      - core-regress-core-ahw2.2
      - core-regress-seabase-ahw2.2
      - core-regress-charsets-cm5.3
      - core-regress-qat-cm5.3
      - core-regress-udr-cm5.3
      - core-regress-catman1-ahw2.2
      - core-regress-compGeneral-ahw2.2
      - core-regress-executor-ahw2.2
      - core-regress-fullstack2-cm5.3
      - core-regress-hive-ahw2.2
      - jdbc_test-cm5.3
      - pyodbc_test-cm5.3
    pre-release-stable:
      - traf-pub-release-ahw2.1
      - traf-pub-debug-ahw2.1
      - phoenix_test_T4-cm5.1
      - phoenix_test_T2-ahw2.1
      - core-regress-core-ahw2.1
      - core-regress-seabase-ahw2.1
      - core-regress-charsets-cm5.1
      - core-regress-qat-cm5.1
      - core-regress-udr-cm5.1
      - core-regress-catman1-ahw2.1
      - core-regress-compGeneral-ahw2.1
      - core-regress-executor-ahw2.1
      - core-regress-fullstack2-cm5.1
      - core-regress-hive-ahw2.1
      - jdbc_test-cm5.1
      - pyodbc_test-cm5.1

  - name: trafodion/dcs
    template:
     - name: dcs-distro
       HW: ahw2.1
       Cld: cm5.1
     - name: dcs-distro
       HW: ahw2.2
       Cld: cm5.3

  - name: trafodion/infra
    check:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax
      - gate-infra-jjb-lint
    gate:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax
      - gate-infra-jjb-lint

  - name: trafodion/manuals
    check:
      - gate-noop
    gate:
      - gate-noop

  - name: trafodion/phoenix_test
    template:
     - name: phxtest-distro
       HW: ahw2.1
       Cld: cm5.1
     - name: phxtest-distro
       HW: ahw2.2
       Cld: cm5.3

  - name: trafodion/install
    check:
      - gate-install-check-for-binary
      - installer-build
    gate:
      - gate-install-check-for-binary
      - pyodbc_test-cm5.3
      - jdbc_test-ahw2.2
      - pyodbc_test-cm5.1-stable
      - jdbc_test-ahw2.1-stable
      - installer-build
    daily:
      - installer-pub
    release:
      - installer-pub
    pre-release:
      - installer-pub

  - name: trafodion/win-odbc64
    check:
      - gate-win-odbc64-check-for-binary
    gate:
      - gate-win-odbc64-check-for-binary

