includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: IndependentPipelineManager
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
          require-approval:
            - verified: [-1, 0]
              username: jenkins
        # From openstack-infra/config SHA-1: 06aada389aa1ceba23bb04b2020689b0d9f06c44
        # Rerun check on change if the results are > 3 days. This is triggered by any activity on the change
        # (in the form of anyone or any bot leaving comments).This should help detect merge conflicts earlier and also let
        # the author know when the patch has zero chances of merging see
        # http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background
        - event: comment-added
          require-approval:
            - username: jenkins
              older-than: 72h
        # From openstack-infra/config SHA-1 :  20f5d2d0034641bc96e822c6846d3b5886dbe119
        # To support the removing of non-integrated jobs (not integrated in 3 days) from gate where their failure is much more expensive.
        # To prevent patches that have been approved with very old checks (older than 3 days) from going to gate where their failure is
        # much more expensive (see http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background)
        - event: comment-added
          require-approval:
            - workflow: 1
            - username: jenkins
              older-than: 72h
        # If check failed, but we get approval, run check again. If it passes, gate will trigger.
        - event: comment-added
          require-approval:
            - verified: -1
              username: jenkins
          approval:
            - workflow: 1
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: DependentPipelineManager
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        # must have passed check, but might have failed gate
        - verified: [-2, 1, 2]
          username: jenkins
          newer-than: 72h
        - workflow: 1
    trigger:
      gerrit:
        # event is approval
        - event: comment-added
          approval:
            - workflow: 1
        # event is code-review, already approved
        - event: comment-added
          approval:
            - code-review: 2
        # event is check test pass, already approved
        - event: comment-added
          approval:
            - verified: 1
          username: jenkins
        # event is reverify comment, already approved
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)( (?:bug|lp)[\s#:]*(\d+))
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]*(_v[0-9]+)?(alpha|beta|candidate|rc|a|b|c|r|g)[0-9]*$
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Test Failures'

  - name: release
    description: When a commit is tagged as a release, this pipeline runs jobs that publish archives and documentation.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]+(_v[0-9]+)?$

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$

  - name: check-full
    description: On-demand extensive check testing. Leave review comment "run check-full".
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*run check-full\s*
    success:
      gerrit: {}
    failure:
      gerrit: {}

  - name: daily
    description: Jobs in this queue are triggered daily.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '30 8 * * *'
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build {change.start_datetime} of {change.project} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build {change.start_datetime} of {change.project} -- Test Failures'

jobs:
  - name: ^.*$
    parameter-function: set_log_url
  - name: ^.*-experimental.*$
    voting: false
  - name: ^phoenix_part.*$
    voting: false

projects:
  - name: trafodion/sandbox
    check:
      - gate-sandbox-check-for-binary
    gate:
      - gate-sandbox-check-for-binary
    silent:
      - gate-sandbox-puppet-lint
      - gate-sandbox-puppet-syntax

  - name: trafodion/core
    check:
      - phoenix_quick-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - core-regress-core-cdh5.1
      - core-regress-seabase-cdh5.1
      - gate-core-check-for-binary
      - core-build-check-cdh5.1
    check-full:
      - phoenix_test-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - core-regress-charsets-cdh5.1
      - core-regress-qat-cdh5.1
      - core-regress-udr-cdh5.1
      - core-regress-catman1-cdh5.1
      - core-regress-compGeneral-cdh5.1
      - core-regress-executor-cdh5.1
      - core-regress-fullstack2-cdh5.1
      - core-regress-hive-cdh5.1
    gate:
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - core-regress-seabase-cdh5.1
      - gate-core-check-for-binary
      - core-build-check-cdh5.1
    daily:
      - traf-pub-release
      - traf-pub-debug
      - core-regress-core-cdh5.1
      - core-regress-core-cm5.1
      - core-regress-core-hdp2.1
      - core-regress-charsets-cdh5.1
      - core-regress-charsets-cm5.1
      - core-regress-charsets-hdp2.1
      - core-regress-qat-cdh5.1
      - core-regress-qat-cm5.1
      - core-regress-qat-hdp2.1
      - core-regress-udr-cdh5.1
      - core-regress-udr-cm5.1
      - core-regress-udr-hdp2.1
      - core-regress-catman1-cdh5.1
      - core-regress-catman1-cm5.1
      - core-regress-catman1-hdp2.1
      - core-regress-compGeneral-cdh5.1
      - core-regress-compGeneral-cm5.1
      - core-regress-compGeneral-hdp2.1
      - core-regress-executor-cdh5.1
      - core-regress-executor-cm5.1
      - core-regress-executor-hdp2.1
      - core-regress-fullstack2-cdh5.1
      - core-regress-fullstack2-cm5.1
      - core-regress-fullstack2-hdp2.1
      - core-regress-hive-cdh5.1
      - core-regress-hive-cm5.1
      - core-regress-hive-hdp2.1
      - core-regress-seabase-cdh5.1
      - core-regress-seabase-cm5.1
      - core-regress-seabase-hdp2.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - phoenix_part1-cm5.1
      - phoenix_part2-cm5.1
      - phoenix_part1-hdp2.1
      - phoenix_part2-hdp2.1
      - pyodbc_test-cdh5.1
      - pyodbc_test-cm5.1
      - pyodbc_test-hdp2.1
      - jdbc_test-cdh5.1
      - jdbc_test-cm5.1
      - jdbc_test-hdp2.1
    release:
      - traf-pub-release
    pre-release:
      - traf-pub-release
      - traf-pub-debug
      - core-regress-core-cdh5.1
      - core-regress-charsets-cdh5.1
      - core-regress-qat-cdh5.1
      - core-regress-udr-cdh5.1
      - core-regress-catman1-cdh5.1
      - core-regress-compGeneral-cdh5.1
      - core-regress-executor-cdh5.1
      - core-regress-fullstack2-cdh5.1
      - core-regress-hive-cdh5.1
      - core-regress-seabase-cdh5.1
      - phoenix_test-cdh5.1
      - pyodbc_test-cdh5.1
      - jdbc_test-cdh5.1

  - name: trafodion/dcs
    check:
      - gate-dcs-check-for-binary
      - dcs-build
      - phoenix_quick-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - pyodbc_test-cdh5.1
      - jdbc_test-cdh5.1
    gate:
      - gate-dcs-check-for-binary
      - dcs-build
      - phoenix_quick-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1
      - pyodbc_test-cdh5.1
      - jdbc_test-cdh5.1
    check-full:
      - phoenix_test-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1

  - name: trafodion/infra
    check:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax
    gate:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax

  - name: trafodion/manuals
    check:
      - gate-noop
    gate:
      - gate-noop

  - name: trafodion/phoenix_test
    check:
      - gate-phoenix_test-check-for-binary
      - phoenix_test-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1

    gate:
      - gate-phoenix_test-check-for-binary
      - phoenix_test-cdh5.1
      - phoenix_part1-cdh5.1
      - phoenix_part2-cdh5.1

  - name: trafodion/install
    check:
      - gate-install-check-for-binary
      - installer-build
    gate:
      - gate-install-check-for-binary
      - installer-build
    daily:
      - installer-pub
    release:
      - installer-pub
    pre-release:
      - installer-pub

  - name: trafodion/win-odbc64
    check:
      - gate-win-odbc64-check-for-binary
    gate:
      - gate-win-odbc64-check-for-binary

