includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: IndependentPipelineManager
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$
        # From openstack-infra/config SHA-1: 06aada389aa1ceba23bb04b2020689b0d9f06c44
        # Rerun check on change if the results are > 3 days. This is triggered by any activity on the change
        # (in the form of anyone or any bot leaving comments).This should help detect merge conflicts earlier and also let
        # the author know when the patch has zero chances of merging see
        # http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background
        - event: comment-added
          require-approval:
            - username: jenkins
              older-than: 72h
        # From openstack-infra/config SHA-1 :  20f5d2d0034641bc96e822c6846d3b5886dbe119
        # To support the removing of non-integrated jobs (not integrated in 3 days) from gate where their failure is much more expensive.
        # To prevent patches that have been approved with very old checks (older than 3 days) from going to gate where their failure is
        # much more expensive (see http://lists.openstack.org/pipermail/openstack-dev/2014-February/027425.html for background)
        - event: comment-added
          require-approval:
            - workflow: 1
            - username: jenkins
              older-than: 72h
        # If check failed, but we get approval, run check again. If it passes, gate will trigger.
        - event: comment-added
          require-approval:
            - verified: -1
              username: jenkins
          approval:
            - workflow: 1
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    failure-message: Build failed.  https://wiki.trafodion.org/wiki/index.php/Code_Reviews#Test_Failures
    manager: DependentPipelineManager
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        # must have passed check, but might have failed gate
        - verified: [-2, 1, 2]
          username: jenkins
          newer-than: 72h
        - workflow: 1
    trigger:
      gerrit:
        # event is approval
        - event: comment-added
          approval:
            - workflow: 1
        # event is check test pass, already approved
        - event: comment-added
          approval:
            - verified: 1
          username: jenkins
        # event is reverify comment, already approved
        - event: comment-added
          # Must use reverify bug # or reverify lp #. Reverify no bug has been disallowed. If it's failing at gate a bug number
          # should be associated with the review even if this is an intermittent issue so it can be tracked.
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*reverify( (?:bug|lp)[\s#:]*(\d+))\s*$
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

#  - name: post
#    description: This pipeline runs jobs that operate after each change is merged.
#    manager: IndependentPipelineManager
#    precedence: low
#    trigger:
#      gerrit:
#        - event: ref-updated
#          ref: ^(?!(devnull|refs/.*)).*$

#  - name: tag
#    description: This pipeline runs jobs in response to any tag event.
#    manager: IndependentPipelineManager
#    precedence: high
#    trigger:
#      gerrit:
#        - event: ref-updated
#          ref: ^refs/tags/.*$

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]*(alpha|beta|candidate|rc|a|b|c|r|g)[0-9]*$
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Pre-Release {change.ref} -- Test Failures'

  - name: release
    description: When a commit is tagged as a release, this pipeline runs jobs that publish archives and documentation.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]+$

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$

#  - name: experimental
#    description: On-demand pipeline for requesting a run against a set of jobs that are not yet gating. Leave review comment of "check experimental" to run jobs in this pipeline.
#    manager: IndependentPipelineManager
#    precedence: low
#    trigger:
#      gerrit:
#        - event: comment-added
#          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*check experimental\s*$
#    success:
#      gerrit:
#        force-message: true
#    failure:
#      gerrit:
#        force-message: true
#
#  - name: periodic
#    description: Jobs in this queue are triggered on a timer.
#    manager: IndependentPipelineManager
#    precedence: low
#    trigger:
#      timer:
#        - time: '0 6 * * *'

  - name: check-full
    description: On-demand extensive check testing. Leave review comment "run check-full".
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^\s*run check-full\s*$
    success:
      gerrit:
        force-message: true
    failure:
      gerrit:
        force-message: true

  - name: daily
    description: Jobs in this queue are triggered daily.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '30 8 * * *'
    success:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build of {change.project} -- Passed All Tests'
    failure:
      smtp:
        from: jenkins@trafodion.org
        to: traf_bld_stats_external.groups.hp.com@external.groups.hp.com
        subject: 'Daily build of {change.project} -- Test Failures'


jobs:
  - name: ^.*$
    parameter-function: set_log_url
  - name: jdbc_test
    voting: false
  - name: jdbc_test-experimental
    voting: false
  - name: phoenix_test
    voting: true
  - name: phoenix_test-experimental
    voting: false
  - name: pyodbc_test
    voting: true
  - name: pyodbc_test-experimental
    voting: false
  - name: gate-infra-puppet-lint
    voting: false

projects:
  - name: trafodion/sandbox
    check:
      - gate-sandbox-check-for-binary
    gate:
      - gate-sandbox-check-for-binary
    silent:
      - gate-sandbox-puppet-lint
      - gate-sandbox-puppet-syntax

  - name: trafodion/core
    check:
      - phoenix_quick
      - core-regress-core
      - gate-core-check-for-binary
    check-full:
      - phoenix_test
      - core-regress-charsets
      - core-regress-qat
      - core-regress-udr
      - core-regress-catman1
      - core-regress-compGeneral
      - core-regress-executor
      - core-regress-hive
      - core-regress-seabase
    gate:
      - phoenix_quick
      - core-regress-core
      - gate-core-check-for-binary
    daily:
      - traf-pub-release
      - traf-pub-debug
      - core-regress-core
      - core-regress-charsets
      - core-regress-qat
      - core-regress-udr
      - core-regress-catman1
      - core-regress-compGeneral
      - core-regress-executor
      - core-regress-hive
      - core-regress-seabase
      - phoenix_test
      - pyodbc_test
      - jdbc_test
    release:
      - traf-pub-release
    pre-release:
      - traf-pub-release
      - traf-pub-debug
      - core-regress-core
      - core-regress-charsets
      - core-regress-qat
      - core-regress-udr
      - core-regress-catman1
      - core-regress-compGeneral
      - core-regress-executor
      - core-regress-hive
      - core-regress-seabase
      - phoenix_test
      - pyodbc_test
      - jdbc_test

  - name: trafodion/dcs
    check:
      - gate-dcs-check-for-binary
      - dcs-build
      - phoenix_quick
      - pyodbc_test
      - jdbc_test
    gate:
      - gate-dcs-check-for-binary
      - dcs-build
      - phoenix_quick
      - pyodbc_test
      - jdbc_test
    check-full:
      - phoenix_test

  - name: trafodion/infra
    check:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax
    gate:
      - gate-infra-check-for-binary
      - gate-infra-puppet-lint
      - gate-infra-puppet-syntax

  - name: trafodion/manuals
    check:
      - gate-noop
    gate:
      - gate-noop

  - name: trafodion/phoenix_test
    check:
      - gate-phoenix_test-check-for-binary
      - phoenix_test

    gate:
      - gate-phoenix_test-check-for-binary
      - phoenix_test

  - name: trafodion/install
    check:
      - gate-install-check-for-binary
      - installer-build
    gate:
      - gate-install-check-for-binary
      - installer-build

  - name: trafodion/win-odbc64
    check:
      - gate-win-odbc64-check-for-binary
    gate:
      - gate-win-odbc64-check-for-binary

